# Site settings
title: Your awesome title
email: richard.hwang201@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
#url: "http://rhwang201.github.com"
url: "http://0.0.0.0:4000"
twitter_username: jekyllrb
github_username:  rhwang201

# Build settings
markdown: kramdown
permalink: pretty
