# Site settings
title: Richard Hwang
email: richard.hwang201@gmail.com
description: "Some interesting things"
baseurl: ""
#url: "http://rhwang201.github.com"
url: "http://0.0.0.0:4000"
github_username:  rhwang201

# Build settings
markdown: kramdown
permalink: pretty

# Sample Jekyll Image Tag settings

name: A Jekyll blog
pygments: true

image:
  source: assets/images/_fullsize
  output: generated
  presets:
    # Proportional preset
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    # Scaled and cropped preset
    half:
      width: 400
      height: 400
